apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata: 
  name: generate-network-policy
spec: 
  rules:
    - name: create-network-policy
      match:
        resources:
          kinds:
            - Namespace
      generate:
        kind: NetworkPolicy
        name: default-deny
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress